### ISSUE TITLE
Get this error code at my console

### ISSUE THREAD

**Issue by HaMiJeng** [galaipa/SimpleRename#14]
[15:52:25] [Server thread/ERROR]: Fatal error trying to convert SimpleRename v11.1:io/github/galaipa/sr/Methods.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for WRITABLE_BOOK. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:176) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:130) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:266) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at io.github.galaipa.sr.SimpleRename.cmdRename(SimpleRename.java:137) ~[?:?]
        at io.github.galaipa.sr.SimpleRename.onCommand(SimpleRename.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by galaipa** [comment]
What MC version are you using?
