### ISSUE TITLE
SimpleRename interferes with TradeSystem plugin

### ISSUE THREAD

**Issue by Repo31c** [galaipa/SimpleRename#15]
Hello,

My server is running Paper 1.13.2 and I am currently using the latest version of SimpleRename & [TradeSystem.](https://www.spigotmc.org/resources/trade-system-custom-layouts.58434/)

TradeSystem uses an anvil for trading currency with players or for setting a name for a custom layout. However, this causes SimpleRename to begin spamming the following error into the console:

`[22:07:33 ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v11.2
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_212]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_212]
at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:23) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor283.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-639]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-639]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-639]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-639]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1309) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.ContainerAnvil.d(ContainerAnvil.java:305) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.ContainerAnvil.a(ContainerAnvil.java:377) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:661) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.PacketPlayInItemName.a(SourceFile:31) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.PacketPlayInItemName.a(SourceFile:8) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-639]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Both plugins still function normally from what I have seen so far and I am still able to complete a trade or use SimpleRename while it is spamming the error, however it is annoying to see that beign spammed in the console since it won't stop until the trade is complete.

**Comment by galaipa** [comment]
Hello,
First of all sorry for the late replay. This should be fixed in SimpleRename v12.0. If not please let me know and I will try to fix it.

**Comment by galaipa** [comment]
Fixed in MC 12.0
