### ISSUE TITLE
spam errors in console 

### ISSUE THREAD

**Issue by elmaslarry** [galaipa/SimpleRename#41]
im using latest version of simplerename and paperspigot 1.12

the error: 

[10:19:59 ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v10.7.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1617]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1617]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1617]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1617]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1102) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:123) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.Slot.f(SourceFile:84) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:80) ~[patched_1.12.2.jar:git-Paper-1617]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryView.setItem(CraftInventoryView.java:54) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.Container.a(Container.java:198) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1963) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1617]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
        at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor259.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.ex

**Comment by galaipa** [comment]
Hello!
Thank you for opening this issue. Could you please give me some more details. When does the exception happen? Do you see any pattern?

**Comment by galaipa** [comment]
Hey!  You say that you are using the latest SimpleRename version, but the log says PrepareAnvilEvent to SimpleRename v10.7.5
A lot of things have changed since then, so please update the plugin to version 13.0 and let me know if you still have the problem.

**Comment by galaipa** [comment]
Closing this issue because of lack of response. Please, feel free to reopen the issue if you still have problems.
