### ISSUE TITLE
 [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.5

### ISSUE THREAD

**Issue by WSpectrumFenixW** [galaipa/SimpleRename#44]
[17:29:59] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.5
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_251]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_251]
	at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:57) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-227]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1501) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.e(ContainerAnvil.java:317) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.a(ContainerAnvil.java:133) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil$1.update(ContainerAnvil.java:42) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:158) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftResultInventory.setItem(CraftResultInventory.java:37) ~[patched_1.15.2.jar:git-Paper-227]
	at simplepets.brainsynder.nms.v1_15_R1.anvil.HandleAnvilGUI.open(HandleAnvilGUI.java:67) ~[?:?]
	at simplepets.brainsynder.nms.anvil.AnvilGUI.open(AnvilGUI.java:37) ~[?:?]
	at simplepets.brainsynder.player.PetOwner.renamePet(PetOwner.java:314) ~[?:?]
	at simplepets.brainsynder.menu.items.list.Name.onClick(Name.java:29) ~[?:?]
	at simplepets.brainsynder.menu.inventory.listeners.DataListener.onClick(DataListener.java:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor625.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-227]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2352) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-227]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[17:29:59] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.5
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_251]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_251]
	at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:57) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-227]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1501) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.e(ContainerAnvil.java:317) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.a(ContainerAnvil.java:393) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:700) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInItemName.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInItemName.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-227]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[17:29:59] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.5
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_251]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_251]
	at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:57) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-227]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-227]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1501) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.e(ContainerAnvil.java:317) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.ContainerAnvil.a(ContainerAnvil.java:393) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:700) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInItemName.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PacketPlayInItemName.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-227]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-227]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by galaipa** [comment]
Fixed in commit  9b5c9de. I will release soon

**Comment by galaipa** [comment]
Thank you for the report BTW
