### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Korinocho** [galaipa/SimpleRename#48]
Im getting this error randomly. Im using Paper 1.16.1 (88) and SimpleRename 13.6

[10:37:06 ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.6
java.lang.NullPointerException: null
        at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:68) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-88]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-88]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-88]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.1.jar:git-Paper-88]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1573) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:68) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:12) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:183) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.ContainerAnvil.a(ContainerAnvil.java:61) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract$2.a(ContainerAnvilAbstract.java:43) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.Container.b(Container.java:371) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.Container.a(Container.java:183) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2429) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-88]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Artuto** [comment]
Bumping this @galaipa

**Comment by galaipa** [comment]
Fixed in [pull request 46 ](https://github.com/galaipa/SimpleRename/pull/46) by [DrBot7](https://github.com/DrBot7)

I will upload a new release soon
