### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DenisJ9798** [galaipa/SimpleRename#54]
[09:53:48] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to SimpleRename v13.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1613]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1102) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:79) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:543) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.shiftClick(ContainerAnvil.java:333) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:251) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1996) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
	at io.github.galaipa.sr.anvilListeners.AnvilListener.recoverColorCodes(AnvilListener.java:30) ~[?:?]
	at io.github.galaipa.sr.anvilListeners.AnvilListener.anvilListener(AnvilListener.java:73) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor472.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1613]
	... 24 more

**Comment by galaipa** [comment]
I would need more details about the error you got. What version of Spigot/Bukkit and SImpleRename are you using? Also, when does the exception happen? Where you interacting with an anvil?

**Comment by QueenOfTheSea21** [comment]
I would assume they're running 1.12.2 (specifically Paper version 1613 instead of spigot) based on the [patched_1.12.2.jar:git-Paper-1613] part of that error message. Seeing how I didn't create this thread, I wouldn't really know but my very best educated guess allows me to say this as I have seen many of these kinds of errors with my servers. (The only reason I am commenting on this, despite what I have just said, is because I noticed there were no other replies and if I am correct and it helps speed a fix up, then I have done my part!)
